commands:
  pipe:
    class: \Driver\Commands\Pipe
  connect:
    class: \Driver\Engines\%engine%
  check-filesystem:
    class: \Driver\Engines\%engine%\Check
  start-sandbox:
    class: \Driver\Engines\%engine%\Sandbox
  export-data-from-source:
    class: \Driver\Engines\%engine%\Export
  import-data-into-sandbox:
    class: \Driver\Engines\%engine%\Sandbox\Import
  export-data-from-sandbox:
    class: \Driver\Engines\%engine%\Sandbox\Export
  shutdown-sandbox:
    class: \Driver\Engines\%engine%\Sandbox\Shutdown
  call-post-webhook:
    class: \Driver\Commands\Webhook\Post