pipes:
  default:
    - 100: connect
    - 200: check-filesystem
    - 300: start-sandbox
    - 400: export-data-from-source
    - 500: import-data-into-sandbox
  # commands go between 501 and 1999
    - 2000: export-data-from-sandbox
    - 2100: shutdown-sandbox
  # export procedures go after 2100
  empty: []