pipes:
  default:
    - setup:
      - 100: connect
      - 200: check-filesystem
      - 300: start-sandbox
#    - 400: export-data-from-source
    - import:
      - 100: import-data-into-sandbox
    - commands:
#   commands go between 501 and 1999
    - export:
      - 2000: export-data-from-sandbox
    - shutdown:
#    - 2100: shutdown-sandbox
  # export procedures go after 2100
  empty: []